### ISSUE TITLE
Cannot deploy with submodules

### ISSUE THREAD

**Issue by ChrisWiegman** [banago/PHPloy#121]
After the initial deployment all subsequent deployments of submodules fail with the following: 

fatal: Invalid symmetric difference expression [hash]...HEAD

**Comment by banago** [comment]
@ChrisWiegman Thanks for reporting. I'll look into this and let you know.

**Comment by banago** [comment]
@ChrisWiegman this is finally fixed - thanks for your patience. To make it work, you will have to manually delete the `.revision` file from the deployed submodules in your server, since that contains the wrong revision, basically the parent repo revision. Please let me know how it goes. Happy deploying!
