### ISSUE TITLE
Installing PHPloy globally on Windows

### ISSUE THREAD

**Issue by corvannoorloos** [banago/PHPloy#186]
Hello,

Trying to install PHPloy **globally** on Windows 7, I'm apparently having some issues finding `phploy.phar`.

Using PHPloy **locally** I've copied the `phploy.phar` into my project folder.
And running `php phploy.phar --version` from my project folder to see if everything is working as expected.

I've created a sample `deploy.ini` by running `php phploy.phar --init`.
And after entering my ftp details running `php phploy.phar` to successfully publish my latest commits.

However, when moving my project's `phploy.phar` to a system recognized path `C:\Windows\System32` (`C:\Windows\System32\phploy.phar`) and running `php phploy.phar --version` from within my project's folder I keep receiving the following notice: `Could not open input file: phploy.phar`.

Also, when adding either `C:\Users\Cor\Desktop\PHPloy` or `C:\Users\Cor\Desktop\PHPloy\bin` as a system recognized variable (trying to grab the original `phploy.phar`), I keep receiving the same notice.

Note, I haven't modified the `C:\Users\Cor\Desktop\PHPloy\phploy.bat` in any way.

Could someone tell what I'm probably just overlooking here?

**Comment by martin-sucha** [comment]
Copying `phploy.phar` to `C:\Windows\System32\phploy.phar` would not work as PHP itself does not look for scripts in `%PATH%`. Windows looks there for executable files (which includes `.bat` files).

Running PHPloy globally works like this: You run `phploy.bat` which in turn itself launches PHP with the correct arguments to run `phploy.phar`.

Therefore `phploy.bat` must be accessible from directories listed in `Path` environment variable and you need to modify `phploy.bat` itself because it contains the path to `phploy.phar` at the bottom of the file. You need to adjust it to point to the correct location of `phploy.phar`.

I'd start by adjusting `phploy.bat` and then checking if I can run `phploy.bat --version` from the directory where it is located. When that works, proceed to add the directory into `Path` environment variable (or just copy it to a directory which is already listed there, but I don't recommend this option).

At this point, you should be able to call PHPloy as `phploy.bat --version` or just `phploy --version` from any directory.

Hope this helps.

**Comment by corvannoorloos** [comment]
That explains. Thanks!

I've added `C:\Users\Cor\Desktop\PHPloy` to my Windows `%PATH%`.

Editing `php C:\path\to\phploy %*` in `phploy.bat` is where things got a bit confusing, as I was only able to run `phploy --version` anywhere using the full filename `php C:\Users\Cor\Desktop\PHPloy\bin\phploy.phar`.

**Comment by desertknight** [comment]
[view my comment here](https://github.com/banago/PHPloy/issues/107#issuecomment-187899972)

Just edit __phploy.bat__ with 
`php C:\Some\Directory\Where\Install\PHPloy\bin\phploy.phar %*`

**Comment by banago** [comment]
:+1:
