### ISSUE TITLE
Copying/moving a directory from upload path to another path on the server after a deployment?

### ISSUE THREAD

**Issue by mrameezraja** [banago/PHPloy#197]
What about copying/moving a directory from upload path to another path on the server after a deployment?

Like we have purging feature. We could have something like

// ['source folder on server', ' destination folder on server']
copy[] = ["/source/public/",'public_html/' ] // folder or file

// ['source folder on server', ' destination folder on server']
move[] = ["/source/public/",'public_html/' ] // folder or file

**Comment by mneimne** [comment]
very useful,I usually have a public folder inside my application, Ill for the project and try to implement this functionality

**Comment by banago** [comment]
I don't see this happening any time soon, but more then happy to pull it if someone implements it.

**Comment by dl1ely** [comment]
Here you are: #219 

This implements a recursive copy for whole directories (no file globbing), omitting missing source directories and overwriting existing files no matter what. I use it to correct an Apache HTTP root dir that is public/ on my machine and www/ on the customers machine when deploying to the customer machine by copying the contents of my public/ into the www/ on the customer machine, which also holds other files that i may not touch.

**Comment by banago** [comment]
@dl1ely amazing job implementing this, thanks. One question though, why did you decide to do this, `
omitting missing source directories`? This will break the site when you add new stuff and it's not take live. Don't you think?

**Comment by dl1ely** [comment]
@banago I do not understand your question, or you do not understand my comment, i am not sure.

If the directory that should be copied ("fromDir" in copy[] = "fromDir/ -> toDir/") is missing, there are two possible ways:
a) Do not check if it exists, just try and list the files in that directory. That yields an ugly error message on the console. 
b) Check if the directory exists, and if not, just skip it. Instead of the ugly error message that would pop up anyway, output an informative error message that the directory cannot be copied as it does not exist at all, and continue.

Do you think a) would be better? I do not think so. If by whatever reason the directory to be copied is not on the server (typo for example), it should be handled gracefully, not by the generic error message of the FTPAdapter that would pop up anyway.

Perhaps i should have written "fromDir" instead of "source directory" in my commit message? Might be misleading. I am „omitting“ something that is not there on the server anyway, it is no deliberate omitting, and i do not see how this can break a site.

**Comment by banago** [comment]
Makes sense now and I agree with your solution. I thought you were skipping inner directories. All good. Thanks a lot for your contribution.

**Comment by dl1ely** [comment]
No, inner directories are copied recursively.

**Comment by banago** [comment]
This is now merged. Thanks a lot.
