### ISSUE TITLE
Create .phployInclude and .phployExclude

### ISSUE THREAD

**Issue by ArbnorZeqiri** [banago/PHPloy#215]
use .phployInclude and .phpExclude instead of include & exclude arrays, respectively (similar to .gitignore). 

p.s. can I work in it ?

**Comment by banago** [comment]
Hey @ArbnorZeqiri thanks for using PHPloy.

I don't find the feature you are suggesting very appealing because it will pollute the working directory unnecessarily. So, I don't see it making it into PHPloy. Is there any particular reason why you need this feature?

On the other hand, there is one feature remaining before PHPloy 4.0 goes stable. It's the logging feature here #32. Would you like to implement it? That would be awesome if you could.
