### ISSUE TITLE
Create and deploy into a new folder

### ISSUE THREAD

**Issue by tubiz** [banago/PHPloy#257]
I use PHPloy to deploy WordPress themes and plugins.

Before I deploy I need to login via SSH and manually create the plugin/theme directory and set the path to the newly created directory

If this isn't done the error below is show
`Oh Snap: Root is invalid or does not exist: /public/wp-content/plugins/plugin-name/`

I think it will be nice for PHPloy to create the plugin-name folder if it doesn't exist before deploying.

**Comment by banago** [comment]
@tubiz you have no idea for how long I've wanted to write this feature, perhaps since I put together PHPloy for the first time. And I've thought of this so many times. I have everything laid out in my head. It will work like this:

    phploy --force

It will create the directory if it does not exist. Thanks for creating the ticket.

**Comment by tubiz** [comment]
@banago thanks for considering this feature request.

Can't wait to have it added to PHPloy.

**Comment by banago** [comment]
@tubiz this feature is now implemented. Enjoy :smile:

**Comment by tubiz** [comment]
Yeah. Thanks @banago 👏🏾
