### ISSUE TITLE
PHPloy and symlinks?

### ISSUE THREAD

**Issue by bobrocke** [banago/PHPloy#315]
Will PHPloy follow symlinks while uploading? I get "failed to upload" errors on symlinked folders.

**Comment by bobrocke** [comment]
I'm working with another project containing symbolic links and PHPloy seems not to be following them. Is it possible to follow them? Do I need a command line switch to allow it?

**Comment by banago** [comment]
@bobrocke I need to look into this, haven't been using symlinks myself.

**Comment by banago** [comment]
@bobrocke the issue is here how Git handles symlinks. Basically for Git symlinks are just a file with some info inside and that's what's given to PHPloy to upload. More: https://stackoverflow.com/questions/954560/how-does-git-handle-symbolic-links

But, you can still manually include files from symlink directories llike this: `include[] = dir/file.php` and they will get uploaded just fine. Just tested it out. 

Happy deployment!
